const cards = [
  {
    id: 0,
    name: 'The Fool',
    image: require('../../assets/cards/the-fool.jpg'),
    description: '새로운 시작, 순수함, 모험심을 나타냅니다.',
    reversedDescription: '무모함, 부주의, 방향성의 결여를 의미합니다.',
  },
  {
    id: 1,
    name: 'The Magician',
    image: require('../../assets/cards/the-magician.jpg'),
    description: '의지력, 창의성, 실행력을 상징합니다.',
    reversedDescription: '기만, 의지 부족, 잠재력의 낭비를 나타냅니다.',
  },
  {
    id: 2,
    name: 'The High Priestess',
    image: require('../../assets/cards/the-high-priestess.jpg'),
    description: '직관, 신비, 내면의 지혜를 나타냅니다.',
    reversedDescription:
      '비밀의 폭로, 직관의 부족, 표면적인 이해를 의미합니다.',
  },
  {
    id: 3,
    name: 'The Empress',
    image: require('../../assets/cards/the-empress.jpg'),
    description: '풍요로움, 창조성, 모성애를 상징합니다.',
    reversedDescription: '창조성의 차단, 의존성, 과잉 보호를 나타냅니다.',
  },
  {
    id: 4,
    name: 'The Emperor',
    image: require('../../assets/cards/the-emperor.jpg'),
    description: '권위, 안정성, 지도력을 나타냅니다.',
    reversedDescription: '권위 남용, 경직성, 통제력 부족을 의미합니다.',
  },
  {
    id: 5,
    name: 'The Hierophant',
    image: require('../../assets/cards/the-hierophant.jpg'),
    description: '전통, 지식, 영적 지도를 상징합니다.',
    reversedDescription: '반항, 전통의 거부, 개성 추구를 나타냅니다.',
  },
  {
    id: 6,
    name: 'The Lovers',
    image: require('../../assets/cards/the-lovers.jpg'),
    description: '사랑, 조화, 선택의 의미를 담고 있습니다.',
    reversedDescription: '불화, 결합의 어려움, 잘못된 선택을 의미합니다.',
  },
  {
    id: 7,
    name: 'The Chariot',
    image: require('../../assets/cards/the-chariot.jpg'),
    description: '의지력, 승리, 전진을 나타냅니다.',
    reversedDescription: '방향성 상실, 실패, 통제력 부족을 의미합니다.',
  },
  {
    id: 8,
    name: 'Strength',
    image: require('../../assets/cards/strength.jpg'),
    description: '용기, 인내, 내적 힘을 상징합니다.',
    reversedDescription: '약함, 불안, 의지력 부족을 나타냅니다.',
  },
  {
    id: 9,
    name: 'The Hermit',
    image: require('../../assets/cards/the-hermit.jpg'),
    description: '내면의 탐구, 고독, 지혜를 나타냅니다.',
    reversedDescription: '고립, 고독감, 방향성의 상실을 의미합니다.',
  },
  {
    id: 10,
    name: 'Wheel of Fortune',
    image: require('../../assets/cards/wheel-of-fortune.jpg'),
    description: '운명, 변화, 행운의 순환을 상징합니다.',
    reversedDescription: '불운, 변화의 저항, 반복되는 악순환을 나타냅니다.',
  },
  {
    id: 11,
    name: 'Justice',
    image: require('../../assets/cards/justice.jpg'),
    description: '균형, 공정함, 책임을 나타냅니다.',
    reversedDescription: '불공정, 불균형, 책임 회피를 의미합니다.',
  },
  {
    id: 12,
    name: 'The Hanged Man',
    image: require('../../assets/cards/the-hanged-man.jpg'),
    description: '새로운 관점, 희생, 수용을 상징합니다.',
    reversedDescription: '지연, 희생의 거부, 집착을 나타냅니다.',
  },
  {
    id: 13,
    name: 'Death',
    image: require('../../assets/cards/death.jpg'),
    description: '변화, 재생, 새로운 시작을 나타냅니다.',
    reversedDescription: '변화의 저항, 정체, 두려움을 의미합니다.',
  },
  {
    id: 14,
    name: 'Temperance',
    image: require('../../assets/cards/temperance.jpg'),
    description: '절제, 조화, 균형을 상징합니다.',
    reversedDescription: '불균형, 극단, 조화의 부족을 나타냅니다.',
  },
  {
    id: 15,
    name: 'The Devil',
    image: require('../../assets/cards/the-devil.jpg'),
    description: '유혹, 속박, 물질적 욕망을 나타냅니다.',
    reversedDescription: '해방, 회복, 속박에서의 탈출을 의미합니다.',
  },
  {
    id: 16,
    name: 'The Tower',
    image: require('../../assets/cards/the-tower.jpg'),
    description: '갑작스러운 변화, 붕괴, 계시를 상징합니다.',
    reversedDescription: '재앙의 회피, 두려움, 변화의 저항을 나타냅니다.',
  },
  {
    id: 17,
    name: 'The Star',
    image: require('../../assets/cards/the-star.jpg'),
    description: '희망, 영감, 치유를 나타냅니다.',
    reversedDescription: '낙담, 자기 의심, 희망 상실을 의미합니다.',
  },
  {
    id: 18,
    name: 'The Moon',
    image: require('../../assets/cards/the-moon.jpg'),
    description: '환상, 직관, 무의식을 상징합니다.',
    reversedDescription:
      '혼란의 해소, 진실의 드러남, 두려움 극복을 나타냅니다.',
  },
  {
    id: 19,
    name: 'The Sun',
    image: require('../../assets/cards/the-sun.jpg'),
    description: '행복, 성공, 활력을 나타냅니다.',
    reversedDescription: '낙관의 부족, 일시적인 성공, 우울함을 의미합니다.',
  },
  {
    id: 20,
    name: 'Judgement',
    image: require('../../assets/cards/judgement.jpg'),
    description: '각성, 부활, 평가를 상징합니다.',
    reversedDescription: '자기 회의, 거부, 결단력 부족을 나타냅니다.',
  },
  {
    id: 21,
    name: 'The World',
    image: require('../../assets/cards/the-world.jpg'),
    description: '완성, 성취, 통합을 나타냅니다.',
    reversedDescription: '미완성, 지연, 목표 달성의 어려움을 의미합니다.',
  },
];

export default cards;
